### ISSUE TITLE
Feature to pass the config file as a command line parameter

### ISSUE THREAD

**Issue by absturztau-be** [fotoente/MiCECo#2]
I'd like to have the option to pass the config file as a command line parameter  (for example`-c /path/to/configfile` )

Reason: in case you want to have this script running for multiple accounts, the only solution right now is to copy the whole folder

If you don't pass the parameter, it should work as it does now, taking the config in the same folder.
but when -c is passed, it should take that config file specified.

**Comment by fotoente** [comment]
Implemented with https://github.com/fotoente/MiCECo/commit/d506ea627d5e49ef0b2850b2938dbc1ac2aaab44
