### ISSUE TITLE
A small request not about this repositories

### ISSUE THREAD

**Issue by gitiy1** [fotoente/MiCECo#8]
Hello, I am  sorry to set issue here but i couldn't find a way to contact with the author. I thought you had set https://github.com/fotoente/Misskey-GPT3-chat-bot before but you deleted the code . Now ChatGPT is really popular and I hope you could consider write a ChatGPT Misskey Bot or just make public or send me the origin code of GPT3. Fediverse would thank you very much.
My contact info is below:
Telegram : https://t.me/iceyear
Mail: mail@iceyear.ml
Misskey: https://starry.ml/@iceyear
Thanks a lot for your hard work!

**Comment by fotoente** [comment]
Let's take that off topic discussion here -> https://mk.absturztau.be/notes/9bf2wldm4n
